# Generated by Django 4.2 on 2024-07-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0002_product_productimage_productmetainformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
