# Generated by Django 4.2 on 2024-07-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0003_alter_productimage_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productmetainformation',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productmetainformation',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
