# Generated by Django 4.2 on 2024-07-07 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0005_alter_productmetainformation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmetainformation',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_information', to='foodordering.product'),
        ),
    ]
